# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.16.5/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.16.5/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/haonanzhao/School/cs5100 Fundamental of AI/game project/tutorials/gym-retro"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/haonanzhao/School/cs5100 Fundamental of AI/game project/tutorials/gym-retro"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.16.5/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.16.5/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.16.5/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.16.5/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/local/Cellar/cmake/3.16.5/bin/cpack --config ./CPackSourceConfig.cmake /Users/haonanzhao/School/cs5100\ Fundamental\ of\ AI/game\ project/tutorials/gym-retro/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/local/Cellar/cmake/3.16.5/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/Cellar/cmake/3.16.5/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.16.5/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.16.5/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.16.5/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.16.5/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/haonanzhao/School/cs5100 Fundamental of AI/game project/tutorials/gym-retro/CMakeFiles" "/Users/haonanzhao/School/cs5100 Fundamental of AI/game project/tutorials/gym-retro/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/haonanzhao/School/cs5100 Fundamental of AI/game project/tutorials/gym-retro/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named retro-base

# Build rule for target.
retro-base: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 retro-base
.PHONY : retro-base

# fast build rule for target.
retro-base/fast:
	$(MAKE) -f CMakeFiles/retro-base.dir/build.make CMakeFiles/retro-base.dir/build
.PHONY : retro-base/fast

#=============================================================================
# Target rules for targets named cores

# Build rule for target.
cores: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cores
.PHONY : cores

# fast build rule for target.
cores/fast:
	$(MAKE) -f CMakeFiles/cores.dir/build.make CMakeFiles/cores.dir/build
.PHONY : cores/fast

#=============================================================================
# Target rules for targets named clean-pce

# Build rule for target.
clean-pce: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clean-pce
.PHONY : clean-pce

# fast build rule for target.
clean-pce/fast:
	$(MAKE) -f CMakeFiles/clean-pce.dir/build.make CMakeFiles/clean-pce.dir/build
.PHONY : clean-pce/fast

#=============================================================================
# Target rules for targets named clean-cores

# Build rule for target.
clean-cores: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clean-cores
.PHONY : clean-cores

# fast build rule for target.
clean-cores/fast:
	$(MAKE) -f CMakeFiles/clean-cores.dir/build.make CMakeFiles/clean-cores.dir/build
.PHONY : clean-cores/fast

#=============================================================================
# Target rules for targets named pce

# Build rule for target.
pce: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pce
.PHONY : pce

# fast build rule for target.
pce/fast:
	$(MAKE) -f CMakeFiles/pce.dir/build.make CMakeFiles/pce.dir/build
.PHONY : pce/fast

#=============================================================================
# Target rules for targets named clean-gba

# Build rule for target.
clean-gba: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clean-gba
.PHONY : clean-gba

# fast build rule for target.
clean-gba/fast:
	$(MAKE) -f CMakeFiles/clean-gba.dir/build.make CMakeFiles/clean-gba.dir/build
.PHONY : clean-gba/fast

#=============================================================================
# Target rules for targets named clean-luajit

# Build rule for target.
clean-luajit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clean-luajit
.PHONY : clean-luajit

# fast build rule for target.
clean-luajit/fast:
	$(MAKE) -f CMakeFiles/clean-luajit.dir/build.make CMakeFiles/clean-luajit.dir/build
.PHONY : clean-luajit/fast

#=============================================================================
# Target rules for targets named gba

# Build rule for target.
gba: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gba
.PHONY : gba

# fast build rule for target.
gba/fast:
	$(MAKE) -f CMakeFiles/gba.dir/build.make CMakeFiles/gba.dir/build
.PHONY : gba/fast

#=============================================================================
# Target rules for targets named genesis

# Build rule for target.
genesis: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 genesis
.PHONY : genesis

# fast build rule for target.
genesis/fast:
	$(MAKE) -f CMakeFiles/genesis.dir/build.make CMakeFiles/genesis.dir/build
.PHONY : genesis/fast

#=============================================================================
# Target rules for targets named clean-gb

# Build rule for target.
clean-gb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clean-gb
.PHONY : clean-gb

# fast build rule for target.
clean-gb/fast:
	$(MAKE) -f CMakeFiles/clean-gb.dir/build.make CMakeFiles/clean-gb.dir/build
.PHONY : clean-gb/fast

#=============================================================================
# Target rules for targets named clean-nes

# Build rule for target.
clean-nes: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clean-nes
.PHONY : clean-nes

# fast build rule for target.
clean-nes/fast:
	$(MAKE) -f CMakeFiles/clean-nes.dir/build.make CMakeFiles/clean-nes.dir/build
.PHONY : clean-nes/fast

#=============================================================================
# Target rules for targets named atari2600

# Build rule for target.
atari2600: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 atari2600
.PHONY : atari2600

# fast build rule for target.
atari2600/fast:
	$(MAKE) -f CMakeFiles/atari2600.dir/build.make CMakeFiles/atari2600.dir/build
.PHONY : atari2600/fast

#=============================================================================
# Target rules for targets named clean-atari2600

# Build rule for target.
clean-atari2600: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clean-atari2600
.PHONY : clean-atari2600

# fast build rule for target.
clean-atari2600/fast:
	$(MAKE) -f CMakeFiles/clean-atari2600.dir/build.make CMakeFiles/clean-atari2600.dir/build
.PHONY : clean-atari2600/fast

#=============================================================================
# Target rules for targets named nes

# Build rule for target.
nes: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nes
.PHONY : nes

# fast build rule for target.
nes/fast:
	$(MAKE) -f CMakeFiles/nes.dir/build.make CMakeFiles/nes.dir/build
.PHONY : nes/fast

#=============================================================================
# Target rules for targets named retro-capnp

# Build rule for target.
retro-capnp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 retro-capnp
.PHONY : retro-capnp

# fast build rule for target.
retro-capnp/fast:
	$(MAKE) -f CMakeFiles/retro-capnp.dir/build.make CMakeFiles/retro-capnp.dir/build
.PHONY : retro-capnp/fast

#=============================================================================
# Target rules for targets named clean-snes

# Build rule for target.
clean-snes: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clean-snes
.PHONY : clean-snes

# fast build rule for target.
clean-snes/fast:
	$(MAKE) -f CMakeFiles/clean-snes.dir/build.make CMakeFiles/clean-snes.dir/build
.PHONY : clean-snes/fast

#=============================================================================
# Target rules for targets named snes

# Build rule for target.
snes: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 snes
.PHONY : snes

# fast build rule for target.
snes/fast:
	$(MAKE) -f CMakeFiles/snes.dir/build.make CMakeFiles/snes.dir/build
.PHONY : snes/fast

#=============================================================================
# Target rules for targets named retro

# Build rule for target.
retro: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 retro
.PHONY : retro

# fast build rule for target.
retro/fast:
	$(MAKE) -f CMakeFiles/retro.dir/build.make CMakeFiles/retro.dir/build
.PHONY : retro/fast

#=============================================================================
# Target rules for targets named clean-genesis

# Build rule for target.
clean-genesis: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clean-genesis
.PHONY : clean-genesis

# fast build rule for target.
clean-genesis/fast:
	$(MAKE) -f CMakeFiles/clean-genesis.dir/build.make CMakeFiles/clean-genesis.dir/build
.PHONY : clean-genesis/fast

#=============================================================================
# Target rules for targets named gb

# Build rule for target.
gb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gb
.PHONY : gb

# fast build rule for target.
gb/fast:
	$(MAKE) -f CMakeFiles/gb.dir/build.make CMakeFiles/gb.dir/build
.PHONY : gb/fast

#=============================================================================
# Target rules for targets named kj-http

# Build rule for target.
kj-http: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kj-http
.PHONY : kj-http

# fast build rule for target.
kj-http/fast:
	$(MAKE) -f third-party/capnproto/c++/src/kj/CMakeFiles/kj-http.dir/build.make third-party/capnproto/c++/src/kj/CMakeFiles/kj-http.dir/build
.PHONY : kj-http/fast

#=============================================================================
# Target rules for targets named kj-test

# Build rule for target.
kj-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kj-test
.PHONY : kj-test

# fast build rule for target.
kj-test/fast:
	$(MAKE) -f third-party/capnproto/c++/src/kj/CMakeFiles/kj-test.dir/build.make third-party/capnproto/c++/src/kj/CMakeFiles/kj-test.dir/build
.PHONY : kj-test/fast

#=============================================================================
# Target rules for targets named kj-async

# Build rule for target.
kj-async: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kj-async
.PHONY : kj-async

# fast build rule for target.
kj-async/fast:
	$(MAKE) -f third-party/capnproto/c++/src/kj/CMakeFiles/kj-async.dir/build.make third-party/capnproto/c++/src/kj/CMakeFiles/kj-async.dir/build
.PHONY : kj-async/fast

#=============================================================================
# Target rules for targets named kj

# Build rule for target.
kj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kj
.PHONY : kj

# fast build rule for target.
kj/fast:
	$(MAKE) -f third-party/capnproto/c++/src/kj/CMakeFiles/kj.dir/build.make third-party/capnproto/c++/src/kj/CMakeFiles/kj.dir/build
.PHONY : kj/fast

#=============================================================================
# Target rules for targets named capnpc

# Build rule for target.
capnpc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 capnpc
.PHONY : capnpc

# fast build rule for target.
capnpc/fast:
	$(MAKE) -f third-party/capnproto/c++/src/capnp/CMakeFiles/capnpc.dir/build.make third-party/capnproto/c++/src/capnp/CMakeFiles/capnpc.dir/build
.PHONY : capnpc/fast

#=============================================================================
# Target rules for targets named capnpc_capnp

# Build rule for target.
capnpc_capnp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 capnpc_capnp
.PHONY : capnpc_capnp

# fast build rule for target.
capnpc_capnp/fast:
	$(MAKE) -f third-party/capnproto/c++/src/capnp/CMakeFiles/capnpc_capnp.dir/build.make third-party/capnproto/c++/src/capnp/CMakeFiles/capnpc_capnp.dir/build
.PHONY : capnpc_capnp/fast

#=============================================================================
# Target rules for targets named capnpc_cpp

# Build rule for target.
capnpc_cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 capnpc_cpp
.PHONY : capnpc_cpp

# fast build rule for target.
capnpc_cpp/fast:
	$(MAKE) -f third-party/capnproto/c++/src/capnp/CMakeFiles/capnpc_cpp.dir/build.make third-party/capnproto/c++/src/capnp/CMakeFiles/capnpc_cpp.dir/build
.PHONY : capnpc_cpp/fast

#=============================================================================
# Target rules for targets named capnp

# Build rule for target.
capnp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 capnp
.PHONY : capnp

# fast build rule for target.
capnp/fast:
	$(MAKE) -f third-party/capnproto/c++/src/capnp/CMakeFiles/capnp.dir/build.make third-party/capnproto/c++/src/capnp/CMakeFiles/capnp.dir/build
.PHONY : capnp/fast

#=============================================================================
# Target rules for targets named capnp_tool

# Build rule for target.
capnp_tool: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 capnp_tool
.PHONY : capnp_tool

# fast build rule for target.
capnp_tool/fast:
	$(MAKE) -f third-party/capnproto/c++/src/capnp/CMakeFiles/capnp_tool.dir/build.make third-party/capnproto/c++/src/capnp/CMakeFiles/capnp_tool.dir/build
.PHONY : capnp_tool/fast

#=============================================================================
# Target rules for targets named capnp-json

# Build rule for target.
capnp-json: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 capnp-json
.PHONY : capnp-json

# fast build rule for target.
capnp-json/fast:
	$(MAKE) -f third-party/capnproto/c++/src/capnp/CMakeFiles/capnp-json.dir/build.make third-party/capnproto/c++/src/capnp/CMakeFiles/capnp-json.dir/build
.PHONY : capnp-json/fast

#=============================================================================
# Target rules for targets named capnp-rpc

# Build rule for target.
capnp-rpc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 capnp-rpc
.PHONY : capnp-rpc

# fast build rule for target.
capnp-rpc/fast:
	$(MAKE) -f third-party/capnproto/c++/src/capnp/CMakeFiles/capnp-rpc.dir/build.make third-party/capnproto/c++/src/capnp/CMakeFiles/capnp-rpc.dir/build
.PHONY : capnp-rpc/fast

#=============================================================================
# Target rules for targets named dist

# Build rule for target.
dist: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dist
.PHONY : dist

# fast build rule for target.
dist/fast:
	$(MAKE) -f third-party/libzip/CMakeFiles/dist.dir/build.make third-party/libzip/CMakeFiles/dist.dir/build
.PHONY : dist/fast

#=============================================================================
# Target rules for targets named zip

# Build rule for target.
zip: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zip
.PHONY : zip

# fast build rule for target.
zip/fast:
	$(MAKE) -f third-party/libzip/lib/CMakeFiles/zip.dir/build.make third-party/libzip/lib/CMakeFiles/zip.dir/build
.PHONY : zip/fast

#=============================================================================
# Target rules for targets named update_zip_err_str

# Build rule for target.
update_zip_err_str: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 update_zip_err_str
.PHONY : update_zip_err_str

# fast build rule for target.
update_zip_err_str/fast:
	$(MAKE) -f third-party/libzip/lib/CMakeFiles/update_zip_err_str.dir/build.make third-party/libzip/lib/CMakeFiles/update_zip_err_str.dir/build
.PHONY : update_zip_err_str/fast

#=============================================================================
# Target rules for targets named update-html

# Build rule for target.
update-html: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 update-html
.PHONY : update-html

# fast build rule for target.
update-html/fast:
	$(MAKE) -f third-party/libzip/man/CMakeFiles/update-html.dir/build.make third-party/libzip/man/CMakeFiles/update-html.dir/build
.PHONY : update-html/fast

#=============================================================================
# Target rules for targets named update_zip_errors

# Build rule for target.
update_zip_errors: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 update_zip_errors
.PHONY : update_zip_errors

# fast build rule for target.
update_zip_errors/fast:
	$(MAKE) -f third-party/libzip/man/CMakeFiles/update_zip_errors.dir/build.make third-party/libzip/man/CMakeFiles/update_zip_errors.dir/build
.PHONY : update_zip_errors/fast

#=============================================================================
# Target rules for targets named update-man

# Build rule for target.
update-man: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 update-man
.PHONY : update-man

# fast build rule for target.
update-man/fast:
	$(MAKE) -f third-party/libzip/man/CMakeFiles/update-man.dir/build.make third-party/libzip/man/CMakeFiles/update-man.dir/build
.PHONY : update-man/fast

#=============================================================================
# Target rules for targets named man

# Build rule for target.
man: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 man
.PHONY : man

# fast build rule for target.
man/fast:
	$(MAKE) -f third-party/libzip/man/CMakeFiles/man.dir/build.make third-party/libzip/man/CMakeFiles/man.dir/build
.PHONY : man/fast

#=============================================================================
# Target rules for targets named zipmerge

# Build rule for target.
zipmerge: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zipmerge
.PHONY : zipmerge

# fast build rule for target.
zipmerge/fast:
	$(MAKE) -f third-party/libzip/src/CMakeFiles/zipmerge.dir/build.make third-party/libzip/src/CMakeFiles/zipmerge.dir/build
.PHONY : zipmerge/fast

#=============================================================================
# Target rules for targets named ziptool

# Build rule for target.
ziptool: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ziptool
.PHONY : ziptool

# fast build rule for target.
ziptool/fast:
	$(MAKE) -f third-party/libzip/src/CMakeFiles/ziptool.dir/build.make third-party/libzip/src/CMakeFiles/ziptool.dir/build
.PHONY : ziptool/fast

#=============================================================================
# Target rules for targets named zipcmp

# Build rule for target.
zipcmp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zipcmp
.PHONY : zipcmp

# fast build rule for target.
zipcmp/fast:
	$(MAKE) -f third-party/libzip/src/CMakeFiles/zipcmp.dir/build.make third-party/libzip/src/CMakeFiles/zipcmp.dir/build
.PHONY : zipcmp/fast

#=============================================================================
# Target rules for targets named testinput

# Build rule for target.
testinput: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testinput
.PHONY : testinput

# fast build rule for target.
testinput/fast:
	$(MAKE) -f third-party/libzip/regress/CMakeFiles/testinput.dir/build.make third-party/libzip/regress/CMakeFiles/testinput.dir/build
.PHONY : testinput/fast

#=============================================================================
# Target rules for targets named cleanup

# Build rule for target.
cleanup: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cleanup
.PHONY : cleanup

# fast build rule for target.
cleanup/fast:
	$(MAKE) -f third-party/libzip/regress/CMakeFiles/cleanup.dir/build.make third-party/libzip/regress/CMakeFiles/cleanup.dir/build
.PHONY : cleanup/fast

#=============================================================================
# Target rules for targets named fread

# Build rule for target.
fread: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fread
.PHONY : fread

# fast build rule for target.
fread/fast:
	$(MAKE) -f third-party/libzip/regress/CMakeFiles/fread.dir/build.make third-party/libzip/regress/CMakeFiles/fread.dir/build
.PHONY : fread/fast

#=============================================================================
# Target rules for targets named nonrandomopen

# Build rule for target.
nonrandomopen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nonrandomopen
.PHONY : nonrandomopen

# fast build rule for target.
nonrandomopen/fast:
	$(MAKE) -f third-party/libzip/regress/CMakeFiles/nonrandomopen.dir/build.make third-party/libzip/regress/CMakeFiles/nonrandomopen.dir/build
.PHONY : nonrandomopen/fast

#=============================================================================
# Target rules for targets named check

# Build rule for target.
check: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check
.PHONY : check

# fast build rule for target.
check/fast:
	$(MAKE) -f third-party/libzip/regress/CMakeFiles/check.dir/build.make third-party/libzip/regress/CMakeFiles/check.dir/build
.PHONY : check/fast

#=============================================================================
# Target rules for targets named fseek

# Build rule for target.
fseek: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fseek
.PHONY : fseek

# fast build rule for target.
fseek/fast:
	$(MAKE) -f third-party/libzip/regress/CMakeFiles/fseek.dir/build.make third-party/libzip/regress/CMakeFiles/fseek.dir/build
.PHONY : fseek/fast

#=============================================================================
# Target rules for targets named ziptool_regress

# Build rule for target.
ziptool_regress: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ziptool_regress
.PHONY : ziptool_regress

# fast build rule for target.
ziptool_regress/fast:
	$(MAKE) -f third-party/libzip/regress/CMakeFiles/ziptool_regress.dir/build.make third-party/libzip/regress/CMakeFiles/ziptool_regress.dir/build
.PHONY : ziptool_regress/fast

#=============================================================================
# Target rules for targets named nonrandomopentest

# Build rule for target.
nonrandomopentest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nonrandomopentest
.PHONY : nonrandomopentest

# fast build rule for target.
nonrandomopentest/fast:
	$(MAKE) -f third-party/libzip/regress/CMakeFiles/nonrandomopentest.dir/build.make third-party/libzip/regress/CMakeFiles/nonrandomopentest.dir/build
.PHONY : nonrandomopentest/fast

#=============================================================================
# Target rules for targets named malloc

# Build rule for target.
malloc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 malloc
.PHONY : malloc

# fast build rule for target.
malloc/fast:
	$(MAKE) -f third-party/libzip/regress/CMakeFiles/malloc.dir/build.make third-party/libzip/regress/CMakeFiles/malloc.dir/build
.PHONY : malloc/fast

#=============================================================================
# Target rules for targets named hole

# Build rule for target.
hole: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hole
.PHONY : hole

# fast build rule for target.
hole/fast:
	$(MAKE) -f third-party/libzip/regress/CMakeFiles/hole.dir/build.make third-party/libzip/regress/CMakeFiles/hole.dir/build
.PHONY : hole/fast

#=============================================================================
# Target rules for targets named add_from_filep

# Build rule for target.
add_from_filep: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 add_from_filep
.PHONY : add_from_filep

# fast build rule for target.
add_from_filep/fast:
	$(MAKE) -f third-party/libzip/regress/CMakeFiles/add_from_filep.dir/build.make third-party/libzip/regress/CMakeFiles/add_from_filep.dir/build
.PHONY : add_from_filep/fast

#=============================================================================
# Target rules for targets named tryopen

# Build rule for target.
tryopen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tryopen
.PHONY : tryopen

# fast build rule for target.
tryopen/fast:
	$(MAKE) -f third-party/libzip/regress/CMakeFiles/tryopen.dir/build.make third-party/libzip/regress/CMakeFiles/tryopen.dir/build
.PHONY : tryopen/fast

#=============================================================================
# Target rules for targets named fopen_unchanged

# Build rule for target.
fopen_unchanged: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fopen_unchanged
.PHONY : fopen_unchanged

# fast build rule for target.
fopen_unchanged/fast:
	$(MAKE) -f third-party/libzip/regress/CMakeFiles/fopen_unchanged.dir/build.make third-party/libzip/regress/CMakeFiles/fopen_unchanged.dir/build
.PHONY : fopen_unchanged/fast

#=============================================================================
# Target rules for targets named can_clone_file

# Build rule for target.
can_clone_file: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 can_clone_file
.PHONY : can_clone_file

# fast build rule for target.
can_clone_file/fast:
	$(MAKE) -f third-party/libzip/regress/CMakeFiles/can_clone_file.dir/build.make third-party/libzip/regress/CMakeFiles/can_clone_file.dir/build
.PHONY : can_clone_file/fast

#=============================================================================
# Target rules for targets named in-memory

# Build rule for target.
in-memory: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 in-memory
.PHONY : in-memory

# fast build rule for target.
in-memory/fast:
	$(MAKE) -f third-party/libzip/examples/CMakeFiles/in-memory.dir/build.make third-party/libzip/examples/CMakeFiles/in-memory.dir/build
.PHONY : in-memory/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) -f third-party/gtest/googlemock/CMakeFiles/gmock.dir/build.make third-party/gtest/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) -f third-party/gtest/googlemock/CMakeFiles/gmock_main.dir/build.make third-party/gtest/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f third-party/gtest/googlemock/gtest/CMakeFiles/gtest_main.dir/build.make third-party/gtest/googlemock/gtest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f third-party/gtest/googlemock/gtest/CMakeFiles/gtest.dir/build.make third-party/gtest/googlemock/gtest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named test-data

# Build rule for target.
test-data: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-data
.PHONY : test-data

# fast build rule for target.
test-data/fast:
	$(MAKE) -f tests/CMakeFiles/test-data.dir/build.make tests/CMakeFiles/test-data.dir/build
.PHONY : test-data/fast

#=============================================================================
# Target rules for targets named test-search

# Build rule for target.
test-search: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-search
.PHONY : test-search

# fast build rule for target.
test-search/fast:
	$(MAKE) -f tests/CMakeFiles/test-search.dir/build.make tests/CMakeFiles/test-search.dir/build
.PHONY : test-search/fast

#=============================================================================
# Target rules for targets named build-tests

# Build rule for target.
build-tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 build-tests
.PHONY : build-tests

# fast build rule for target.
build-tests/fast:
	$(MAKE) -f tests/CMakeFiles/build-tests.dir/build.make tests/CMakeFiles/build-tests.dir/build
.PHONY : build-tests/fast

#=============================================================================
# Target rules for targets named test-script

# Build rule for target.
test-script: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-script
.PHONY : test-script

# fast build rule for target.
test-script/fast:
	$(MAKE) -f tests/CMakeFiles/test-script.dir/build.make tests/CMakeFiles/test-script.dir/build
.PHONY : test-script/fast

#=============================================================================
# Target rules for targets named test-memory

# Build rule for target.
test-memory: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-memory
.PHONY : test-memory

# fast build rule for target.
test-memory/fast:
	$(MAKE) -f tests/CMakeFiles/test-memory.dir/build.make tests/CMakeFiles/test-memory.dir/build
.PHONY : test-memory/fast

#=============================================================================
# Target rules for targets named test-emulator

# Build rule for target.
test-emulator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-emulator
.PHONY : test-emulator

# fast build rule for target.
test-emulator/fast:
	$(MAKE) -f tests/CMakeFiles/test-emulator.dir/build.make tests/CMakeFiles/test-emulator.dir/build
.PHONY : test-emulator/fast

#=============================================================================
# Target rules for targets named test-memory-overlay

# Build rule for target.
test-memory-overlay: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-memory-overlay
.PHONY : test-memory-overlay

# fast build rule for target.
test-memory-overlay/fast:
	$(MAKE) -f tests/CMakeFiles/test-memory-overlay.dir/build.make tests/CMakeFiles/test-memory-overlay.dir/build
.PHONY : test-memory-overlay/fast

src/coreinfo.o: src/coreinfo.cpp.o

.PHONY : src/coreinfo.o

# target to build an object file
src/coreinfo.cpp.o:
	$(MAKE) -f CMakeFiles/retro-base.dir/build.make CMakeFiles/retro-base.dir/src/coreinfo.cpp.o
.PHONY : src/coreinfo.cpp.o

src/coreinfo.i: src/coreinfo.cpp.i

.PHONY : src/coreinfo.i

# target to preprocess a source file
src/coreinfo.cpp.i:
	$(MAKE) -f CMakeFiles/retro-base.dir/build.make CMakeFiles/retro-base.dir/src/coreinfo.cpp.i
.PHONY : src/coreinfo.cpp.i

src/coreinfo.s: src/coreinfo.cpp.s

.PHONY : src/coreinfo.s

# target to generate assembly for a file
src/coreinfo.cpp.s:
	$(MAKE) -f CMakeFiles/retro-base.dir/build.make CMakeFiles/retro-base.dir/src/coreinfo.cpp.s
.PHONY : src/coreinfo.cpp.s

src/data-capnp.o: src/data-capnp.cpp.o

.PHONY : src/data-capnp.o

# target to build an object file
src/data-capnp.cpp.o:
	$(MAKE) -f CMakeFiles/retro-capnp.dir/build.make CMakeFiles/retro-capnp.dir/src/data-capnp.cpp.o
.PHONY : src/data-capnp.cpp.o

src/data-capnp.i: src/data-capnp.cpp.i

.PHONY : src/data-capnp.i

# target to preprocess a source file
src/data-capnp.cpp.i:
	$(MAKE) -f CMakeFiles/retro-capnp.dir/build.make CMakeFiles/retro-capnp.dir/src/data-capnp.cpp.i
.PHONY : src/data-capnp.cpp.i

src/data-capnp.s: src/data-capnp.cpp.s

.PHONY : src/data-capnp.s

# target to generate assembly for a file
src/data-capnp.cpp.s:
	$(MAKE) -f CMakeFiles/retro-capnp.dir/build.make CMakeFiles/retro-capnp.dir/src/data-capnp.cpp.s
.PHONY : src/data-capnp.cpp.s

src/data.o: src/data.cpp.o

.PHONY : src/data.o

# target to build an object file
src/data.cpp.o:
	$(MAKE) -f CMakeFiles/retro-base.dir/build.make CMakeFiles/retro-base.dir/src/data.cpp.o
.PHONY : src/data.cpp.o

src/data.i: src/data.cpp.i

.PHONY : src/data.i

# target to preprocess a source file
src/data.cpp.i:
	$(MAKE) -f CMakeFiles/retro-base.dir/build.make CMakeFiles/retro-base.dir/src/data.cpp.i
.PHONY : src/data.cpp.i

src/data.s: src/data.cpp.s

.PHONY : src/data.s

# target to generate assembly for a file
src/data.cpp.s:
	$(MAKE) -f CMakeFiles/retro-base.dir/build.make CMakeFiles/retro-base.dir/src/data.cpp.s
.PHONY : src/data.cpp.s

src/emulator.o: src/emulator.cpp.o

.PHONY : src/emulator.o

# target to build an object file
src/emulator.cpp.o:
	$(MAKE) -f CMakeFiles/retro-base.dir/build.make CMakeFiles/retro-base.dir/src/emulator.cpp.o
.PHONY : src/emulator.cpp.o

src/emulator.i: src/emulator.cpp.i

.PHONY : src/emulator.i

# target to preprocess a source file
src/emulator.cpp.i:
	$(MAKE) -f CMakeFiles/retro-base.dir/build.make CMakeFiles/retro-base.dir/src/emulator.cpp.i
.PHONY : src/emulator.cpp.i

src/emulator.s: src/emulator.cpp.s

.PHONY : src/emulator.s

# target to generate assembly for a file
src/emulator.cpp.s:
	$(MAKE) -f CMakeFiles/retro-base.dir/build.make CMakeFiles/retro-base.dir/src/emulator.cpp.s
.PHONY : src/emulator.cpp.s

src/imageops.o: src/imageops.cpp.o

.PHONY : src/imageops.o

# target to build an object file
src/imageops.cpp.o:
	$(MAKE) -f CMakeFiles/retro-base.dir/build.make CMakeFiles/retro-base.dir/src/imageops.cpp.o
.PHONY : src/imageops.cpp.o

src/imageops.i: src/imageops.cpp.i

.PHONY : src/imageops.i

# target to preprocess a source file
src/imageops.cpp.i:
	$(MAKE) -f CMakeFiles/retro-base.dir/build.make CMakeFiles/retro-base.dir/src/imageops.cpp.i
.PHONY : src/imageops.cpp.i

src/imageops.s: src/imageops.cpp.s

.PHONY : src/imageops.s

# target to generate assembly for a file
src/imageops.cpp.s:
	$(MAKE) -f CMakeFiles/retro-base.dir/build.make CMakeFiles/retro-base.dir/src/imageops.cpp.s
.PHONY : src/imageops.cpp.s

src/memory.o: src/memory.cpp.o

.PHONY : src/memory.o

# target to build an object file
src/memory.cpp.o:
	$(MAKE) -f CMakeFiles/retro-base.dir/build.make CMakeFiles/retro-base.dir/src/memory.cpp.o
.PHONY : src/memory.cpp.o

src/memory.i: src/memory.cpp.i

.PHONY : src/memory.i

# target to preprocess a source file
src/memory.cpp.i:
	$(MAKE) -f CMakeFiles/retro-base.dir/build.make CMakeFiles/retro-base.dir/src/memory.cpp.i
.PHONY : src/memory.cpp.i

src/memory.s: src/memory.cpp.s

.PHONY : src/memory.s

# target to generate assembly for a file
src/memory.cpp.s:
	$(MAKE) -f CMakeFiles/retro-base.dir/build.make CMakeFiles/retro-base.dir/src/memory.cpp.s
.PHONY : src/memory.cpp.s

src/movie-bk2.o: src/movie-bk2.cpp.o

.PHONY : src/movie-bk2.o

# target to build an object file
src/movie-bk2.cpp.o:
	$(MAKE) -f CMakeFiles/retro-base.dir/build.make CMakeFiles/retro-base.dir/src/movie-bk2.cpp.o
.PHONY : src/movie-bk2.cpp.o

src/movie-bk2.i: src/movie-bk2.cpp.i

.PHONY : src/movie-bk2.i

# target to preprocess a source file
src/movie-bk2.cpp.i:
	$(MAKE) -f CMakeFiles/retro-base.dir/build.make CMakeFiles/retro-base.dir/src/movie-bk2.cpp.i
.PHONY : src/movie-bk2.cpp.i

src/movie-bk2.s: src/movie-bk2.cpp.s

.PHONY : src/movie-bk2.s

# target to generate assembly for a file
src/movie-bk2.cpp.s:
	$(MAKE) -f CMakeFiles/retro-base.dir/build.make CMakeFiles/retro-base.dir/src/movie-bk2.cpp.s
.PHONY : src/movie-bk2.cpp.s

src/movie-fm2.o: src/movie-fm2.cpp.o

.PHONY : src/movie-fm2.o

# target to build an object file
src/movie-fm2.cpp.o:
	$(MAKE) -f CMakeFiles/retro-base.dir/build.make CMakeFiles/retro-base.dir/src/movie-fm2.cpp.o
.PHONY : src/movie-fm2.cpp.o

src/movie-fm2.i: src/movie-fm2.cpp.i

.PHONY : src/movie-fm2.i

# target to preprocess a source file
src/movie-fm2.cpp.i:
	$(MAKE) -f CMakeFiles/retro-base.dir/build.make CMakeFiles/retro-base.dir/src/movie-fm2.cpp.i
.PHONY : src/movie-fm2.cpp.i

src/movie-fm2.s: src/movie-fm2.cpp.s

.PHONY : src/movie-fm2.s

# target to generate assembly for a file
src/movie-fm2.cpp.s:
	$(MAKE) -f CMakeFiles/retro-base.dir/build.make CMakeFiles/retro-base.dir/src/movie-fm2.cpp.s
.PHONY : src/movie-fm2.cpp.s

src/movie.o: src/movie.cpp.o

.PHONY : src/movie.o

# target to build an object file
src/movie.cpp.o:
	$(MAKE) -f CMakeFiles/retro-base.dir/build.make CMakeFiles/retro-base.dir/src/movie.cpp.o
.PHONY : src/movie.cpp.o

src/movie.i: src/movie.cpp.i

.PHONY : src/movie.i

# target to preprocess a source file
src/movie.cpp.i:
	$(MAKE) -f CMakeFiles/retro-base.dir/build.make CMakeFiles/retro-base.dir/src/movie.cpp.i
.PHONY : src/movie.cpp.i

src/movie.s: src/movie.cpp.s

.PHONY : src/movie.s

# target to generate assembly for a file
src/movie.cpp.s:
	$(MAKE) -f CMakeFiles/retro-base.dir/build.make CMakeFiles/retro-base.dir/src/movie.cpp.s
.PHONY : src/movie.cpp.s

src/retro.o: src/retro.cpp.o

.PHONY : src/retro.o

# target to build an object file
src/retro.cpp.o:
	$(MAKE) -f CMakeFiles/retro.dir/build.make CMakeFiles/retro.dir/src/retro.cpp.o
.PHONY : src/retro.cpp.o

src/retro.i: src/retro.cpp.i

.PHONY : src/retro.i

# target to preprocess a source file
src/retro.cpp.i:
	$(MAKE) -f CMakeFiles/retro.dir/build.make CMakeFiles/retro.dir/src/retro.cpp.i
.PHONY : src/retro.cpp.i

src/retro.s: src/retro.cpp.s

.PHONY : src/retro.s

# target to generate assembly for a file
src/retro.cpp.s:
	$(MAKE) -f CMakeFiles/retro.dir/build.make CMakeFiles/retro.dir/src/retro.cpp.s
.PHONY : src/retro.cpp.s

src/script-lua.o: src/script-lua.cpp.o

.PHONY : src/script-lua.o

# target to build an object file
src/script-lua.cpp.o:
	$(MAKE) -f CMakeFiles/retro-base.dir/build.make CMakeFiles/retro-base.dir/src/script-lua.cpp.o
.PHONY : src/script-lua.cpp.o

src/script-lua.i: src/script-lua.cpp.i

.PHONY : src/script-lua.i

# target to preprocess a source file
src/script-lua.cpp.i:
	$(MAKE) -f CMakeFiles/retro-base.dir/build.make CMakeFiles/retro-base.dir/src/script-lua.cpp.i
.PHONY : src/script-lua.cpp.i

src/script-lua.s: src/script-lua.cpp.s

.PHONY : src/script-lua.s

# target to generate assembly for a file
src/script-lua.cpp.s:
	$(MAKE) -f CMakeFiles/retro-base.dir/build.make CMakeFiles/retro-base.dir/src/script-lua.cpp.s
.PHONY : src/script-lua.cpp.s

src/script.o: src/script.cpp.o

.PHONY : src/script.o

# target to build an object file
src/script.cpp.o:
	$(MAKE) -f CMakeFiles/retro-base.dir/build.make CMakeFiles/retro-base.dir/src/script.cpp.o
.PHONY : src/script.cpp.o

src/script.i: src/script.cpp.i

.PHONY : src/script.i

# target to preprocess a source file
src/script.cpp.i:
	$(MAKE) -f CMakeFiles/retro-base.dir/build.make CMakeFiles/retro-base.dir/src/script.cpp.i
.PHONY : src/script.cpp.i

src/script.s: src/script.cpp.s

.PHONY : src/script.s

# target to generate assembly for a file
src/script.cpp.s:
	$(MAKE) -f CMakeFiles/retro-base.dir/build.make CMakeFiles/retro-base.dir/src/script.cpp.s
.PHONY : src/script.cpp.s

src/search.o: src/search.cpp.o

.PHONY : src/search.o

# target to build an object file
src/search.cpp.o:
	$(MAKE) -f CMakeFiles/retro-base.dir/build.make CMakeFiles/retro-base.dir/src/search.cpp.o
.PHONY : src/search.cpp.o

src/search.i: src/search.cpp.i

.PHONY : src/search.i

# target to preprocess a source file
src/search.cpp.i:
	$(MAKE) -f CMakeFiles/retro-base.dir/build.make CMakeFiles/retro-base.dir/src/search.cpp.i
.PHONY : src/search.cpp.i

src/search.s: src/search.cpp.s

.PHONY : src/search.s

# target to generate assembly for a file
src/search.cpp.s:
	$(MAKE) -f CMakeFiles/retro-base.dir/build.make CMakeFiles/retro-base.dir/src/search.cpp.s
.PHONY : src/search.cpp.s

src/serialize.capnp.o: src/serialize.capnp.c++.o

.PHONY : src/serialize.capnp.o

# target to build an object file
src/serialize.capnp.c++.o:
	$(MAKE) -f CMakeFiles/retro-capnp.dir/build.make CMakeFiles/retro-capnp.dir/src/serialize.capnp.c++.o
.PHONY : src/serialize.capnp.c++.o

src/serialize.capnp.i: src/serialize.capnp.c++.i

.PHONY : src/serialize.capnp.i

# target to preprocess a source file
src/serialize.capnp.c++.i:
	$(MAKE) -f CMakeFiles/retro-capnp.dir/build.make CMakeFiles/retro-capnp.dir/src/serialize.capnp.c++.i
.PHONY : src/serialize.capnp.c++.i

src/serialize.capnp.s: src/serialize.capnp.c++.s

.PHONY : src/serialize.capnp.s

# target to generate assembly for a file
src/serialize.capnp.c++.s:
	$(MAKE) -f CMakeFiles/retro-capnp.dir/build.make CMakeFiles/retro-capnp.dir/src/serialize.capnp.c++.s
.PHONY : src/serialize.capnp.c++.s

src/utils.o: src/utils.cpp.o

.PHONY : src/utils.o

# target to build an object file
src/utils.cpp.o:
	$(MAKE) -f CMakeFiles/retro-base.dir/build.make CMakeFiles/retro-base.dir/src/utils.cpp.o
.PHONY : src/utils.cpp.o

src/utils.i: src/utils.cpp.i

.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cpp.i:
	$(MAKE) -f CMakeFiles/retro-base.dir/build.make CMakeFiles/retro-base.dir/src/utils.cpp.i
.PHONY : src/utils.cpp.i

src/utils.s: src/utils.cpp.s

.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cpp.s:
	$(MAKE) -f CMakeFiles/retro-base.dir/build.make CMakeFiles/retro-base.dir/src/utils.cpp.s
.PHONY : src/utils.cpp.s

src/zipfile.o: src/zipfile.cpp.o

.PHONY : src/zipfile.o

# target to build an object file
src/zipfile.cpp.o:
	$(MAKE) -f CMakeFiles/retro-base.dir/build.make CMakeFiles/retro-base.dir/src/zipfile.cpp.o
.PHONY : src/zipfile.cpp.o

src/zipfile.i: src/zipfile.cpp.i

.PHONY : src/zipfile.i

# target to preprocess a source file
src/zipfile.cpp.i:
	$(MAKE) -f CMakeFiles/retro-base.dir/build.make CMakeFiles/retro-base.dir/src/zipfile.cpp.i
.PHONY : src/zipfile.cpp.i

src/zipfile.s: src/zipfile.cpp.s

.PHONY : src/zipfile.s

# target to generate assembly for a file
src/zipfile.cpp.s:
	$(MAKE) -f CMakeFiles/retro-base.dir/build.make CMakeFiles/retro-base.dir/src/zipfile.cpp.s
.PHONY : src/zipfile.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/local"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... package_source"
	@echo "... package"
	@echo "... test"
	@echo "... retro-base"
	@echo "... cores"
	@echo "... clean-pce"
	@echo "... clean-cores"
	@echo "... install/strip"
	@echo "... pce"
	@echo "... clean-gba"
	@echo "... clean-luajit"
	@echo "... gba"
	@echo "... genesis"
	@echo "... clean-gb"
	@echo "... clean-nes"
	@echo "... atari2600"
	@echo "... clean-atari2600"
	@echo "... nes"
	@echo "... retro-capnp"
	@echo "... clean-snes"
	@echo "... snes"
	@echo "... retro"
	@echo "... clean-genesis"
	@echo "... install"
	@echo "... gb"
	@echo "... kj-http"
	@echo "... kj-test"
	@echo "... kj-async"
	@echo "... kj"
	@echo "... capnpc"
	@echo "... capnpc_capnp"
	@echo "... capnpc_cpp"
	@echo "... capnp"
	@echo "... capnp_tool"
	@echo "... capnp-json"
	@echo "... capnp-rpc"
	@echo "... dist"
	@echo "... zip"
	@echo "... update_zip_err_str"
	@echo "... update-html"
	@echo "... update_zip_errors"
	@echo "... update-man"
	@echo "... man"
	@echo "... zipmerge"
	@echo "... ziptool"
	@echo "... zipcmp"
	@echo "... testinput"
	@echo "... cleanup"
	@echo "... fread"
	@echo "... nonrandomopen"
	@echo "... check"
	@echo "... fseek"
	@echo "... ziptool_regress"
	@echo "... nonrandomopentest"
	@echo "... malloc"
	@echo "... hole"
	@echo "... add_from_filep"
	@echo "... tryopen"
	@echo "... fopen_unchanged"
	@echo "... can_clone_file"
	@echo "... in-memory"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest_main"
	@echo "... gtest"
	@echo "... test-data"
	@echo "... test-search"
	@echo "... build-tests"
	@echo "... test-script"
	@echo "... test-memory"
	@echo "... test-emulator"
	@echo "... test-memory-overlay"
	@echo "... src/coreinfo.o"
	@echo "... src/coreinfo.i"
	@echo "... src/coreinfo.s"
	@echo "... src/data-capnp.o"
	@echo "... src/data-capnp.i"
	@echo "... src/data-capnp.s"
	@echo "... src/data.o"
	@echo "... src/data.i"
	@echo "... src/data.s"
	@echo "... src/emulator.o"
	@echo "... src/emulator.i"
	@echo "... src/emulator.s"
	@echo "... src/imageops.o"
	@echo "... src/imageops.i"
	@echo "... src/imageops.s"
	@echo "... src/memory.o"
	@echo "... src/memory.i"
	@echo "... src/memory.s"
	@echo "... src/movie-bk2.o"
	@echo "... src/movie-bk2.i"
	@echo "... src/movie-bk2.s"
	@echo "... src/movie-fm2.o"
	@echo "... src/movie-fm2.i"
	@echo "... src/movie-fm2.s"
	@echo "... src/movie.o"
	@echo "... src/movie.i"
	@echo "... src/movie.s"
	@echo "... src/retro.o"
	@echo "... src/retro.i"
	@echo "... src/retro.s"
	@echo "... src/script-lua.o"
	@echo "... src/script-lua.i"
	@echo "... src/script-lua.s"
	@echo "... src/script.o"
	@echo "... src/script.i"
	@echo "... src/script.s"
	@echo "... src/search.o"
	@echo "... src/search.i"
	@echo "... src/search.s"
	@echo "... src/serialize.capnp.o"
	@echo "... src/serialize.capnp.i"
	@echo "... src/serialize.capnp.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
	@echo "... src/zipfile.o"
	@echo "... src/zipfile.i"
	@echo "... src/zipfile.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

